### ISSUE TITLE
Use Client-side ID rather than Mobile Key

### ISSUE THREAD

**Issue by theboyknowsclass** [launchdarkly/xamarin-client-sdk#30]
Hi, our Security team have raised a question about whether we can use the Client-side ID instead of the Mobile API Key as we are worried about the decompilation of our c# code exposing the key.

Do you have support for this / is it on a roadmap?

kind regards

Gautam Bhatnagar

**Comment by bwoskow-ld** [comment]
Hi @theboyknowsclass,

A "mobile key" is not considered confidential. As such there is minimal risk if it is exposed in a decompiled application. In general, we do not recommend embedding any secrets (for LaunchDarkly or otherwise) in binaries which are distributed onto customers' own devices for this very reason.

I recommend that you take a look at [our documentation](https://docs.launchdarkly.com/sdk/concepts/client-side-server-side#keys) on this topic. A mobile key grants _read-only_ access to _evaluated values_ of feature flags _which were opted into scope for mobile evaluation_. The three italicized items are worth emphasizing: mobile keys do **not** grant 1) write access to flags, 2) read access to targeting rules, or 3) read access to flags which were not explicitly enabled for mobile evaluation. At a higher level, mobile keys can be understood to only grant access to the specific sets of functionality that mobile SDKs offer -- nothing more -- and only for flags opted into for mobile evaluation.

For these reasons we do not have any plans to change this SDK to use a client-side ID instead of mobile key.

If you ever have specific concerns about a mobile key getting exposed we offer the ability to rotate the key, however, please note that doing so would affect any active customers using that mobile key with your software.

I'm going to close this task, but let me know if you have any further questions.

Cheers,
@bwoskow-ld

**Comment by theboyknowsclass** [comment]
hi @bwoskow-ld thanks for the quick response!

**Comment by bwoskow-ld** [comment]
Great question. To be frank, there's little difference in client-side IDs and mobile keys these days. Several years ago, when LaunchDarkly initially rolled out server-side and client-side SDKs, the distinct differences between the three kinds of identifiers (those two plus SDK keys) was:

1. SDK keys could access _flag targeting rules_, thus exposing potentially sensitive business rules or customer identifiers
2. Mobile keys could not access flag targeting rules and instead could only access _evaluated flag values for a particular user_, and could do so for _all flags associated with the corresponding environment_
3. Client-side ID similarly could only access _evaluated flag values for a particular user_, but only for _a subset of an environment's flags_ as denoted by whichever flags are opted into client-side evaluation

At that time there was a notable difference between #2 and #3 (all flags versus a subset), and as a result LaunchDarkly added the ability to rotate a mobile key.

Then, last year, we improved our security / access control capabilities by expanding the opt-in functionality to SDKs using mobile keys. It was no longer the case that mobile keys would always have access to all flags in the corresponding environment. By this time the two identifiers are effectively the same, except for the fact that mobile keys can still be reset, whereas client-side IDs cannot be.

Cheers,
@bwoskow-ld
